import { createSlice } from "@reduxjs/toolkit";

export const genreOrCategory = createSlice({
  name: "genreOrCategory",
  initialState: {
    genreIdOrCategoryName: "",
    page: 1,
    searchQuery: "",
  },
  //* manually created this unlike in th etoolkit
  // Define reducer functions to update the state
  reducers: {
    // Reducer  to update the selected genre or category
    selectGenreOrCategory: (state, action) => {
      // Update the genreIdOrCategoryName state with the payload received from the action
      state.genreIdOrCategoryName = action.payload;
      // saving data  to store
      console.log(action.payload);
    },
  },
});

// Extract and export the action creator generated by createSlice
export const { selectGenreOrCategory } = genreOrCategory.actions;

// Export the reducer function generated by createSlice
export default genreOrCategory.reducer;
